version: '3.0'

services:
  rabbit-mq:
    image: rabbitmq:3.7-management
    container_name: rabbit-mq
    networks:
      - ngrok-net
      
  ngrok:
    ports:
      - 4040:4040
    image: "gtriggiano/ngrok-tunnel"
    container_name: ngrok
    stdin_open: true
    tty: true
    environment:
        TARGET_HOST: "192.168.0.106"
        TARGET_PORT: 27014
  
  web-apigateway:
    ports:
      - 4444:4444
    networks:
      - ngrok-net
    environment:
      ASPNETCORE_URLS: http://+:4444
      ASPNETCORE_ENVIRONMENT: Development
      'ApiUrls:AuthApi': "https://192.168.0.106:27015/"
    image: "web-apigateway"
    container_name: web-apigateway
    depends_on:
      - rabbit-mq
      
  auth-api:
    ports:
      - 27015:27015
    networks:
      - ngrok-net
    environment:
      ASPNETCORE_URLS: http://+:27015
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMqHost: "rabbit-mq"
      'ConnectionStrings:local': "Server=192.168.0.106,1433;Database=AuthContext;User=MadJuns;Password=100895;"
      
    image: "auth-api"
    container_name: auth-api
    depends_on:
      - rabbit-mq
      
  email-notifications:
    ports:
      - 27016:27016
    networks:
      - ngrok-net
    environment:
      RabbitMqHost: "rabbit-mq"
      
    image: "email-notifications"
    container_name: email-notifications
    depends_on:
      - rabbit-mq
    
  users-api:
    ports:
      - 27017:27017
    networks:
      - ngrok-net
    environment:
      ASPNETCORE_URLS: http://+:27017
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMqHost: "rabbit-mq"
      'ConnectionStrings:local': "Server=192.168.0.106,1433;Database=UsersContext;User=MadJuns;Password=100895;"
      
    image: "users-api"
    container_name: users-api
    depends_on:
      - rabbit-mq
    
networks:
  ngrok-net:
    external: false