// <auto-generated />
using System;
using Auth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auth.Data.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20190805182331_AddedAccountSeedData")]
    partial class AddedAccountSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Auth.Core.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDay");

                    b.Property<string>("Email");

                    b.Property<string>("ForgotPasswordToken");

                    b.Property<bool>("IsEmailVerified");

                    b.Property<string>("Password");

                    b.Property<string>("ProviderId");

                    b.Property<int>("SystemRole");

                    b.Property<string>("UserName");

                    b.Property<string>("VerifyEmailToken");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("140505f0-9b68-4b74-b33a-51979ddcd8d2"),
                            BirthDay = new DateTime(2019, 8, 5, 21, 23, 31, 83, DateTimeKind.Local).AddTicks(4230),
                            Email = "admin@madjuns.com",
                            IsEmailVerified = false,
                            Password = "BA3253876AED6BC22D4A6FF53D8406C6AD864195ED144AB5C87621B6C233B548BAEAE6956DF346EC8C17F5EA10F35EE3CBC514797ED7DDD3145464E2A0BAB413",
                            SystemRole = 0,
                            UserName = "super admin",
                            VerifyEmailToken = "344d5814-9b5a-466b-9c44-3889c1be4ab5"
                        },
                        new
                        {
                            Id = new Guid("ecf75ef2-63ee-4e38-86e8-1baaf91789ac"),
                            BirthDay = new DateTime(2019, 8, 5, 21, 23, 31, 86, DateTimeKind.Local).AddTicks(8969),
                            Email = "moderator@madjuns.com",
                            IsEmailVerified = false,
                            Password = "BA3253876AED6BC22D4A6FF53D8406C6AD864195ED144AB5C87621B6C233B548BAEAE6956DF346EC8C17F5EA10F35EE3CBC514797ED7DDD3145464E2A0BAB413",
                            SystemRole = 1,
                            UserName = "moderaot",
                            VerifyEmailToken = "98179b8e-8b95-4df8-9ec9-92b88518fb89"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
